stages:
  - deploy

deploy_monitor_dev:
  stage: deploy
  tags:
    - tecrep-app-dev-16  # ← Runner específico en el servidor
  variables:
    REGISTRY: git.tigopa.local:5050
    IMAGE: tigo/tecrep/monitor
    IMAGE_TAG: "toc"
    COMPOSE_FILE: docker-compose.yml
    DEPLOY_DIR: /u01/monitor

  rules:
    # Ejecutar solo si es push o merge hacia la rama toc-sat-dev
    - if: '$CI_COMMIT_BRANCH == "toc-sat-dev"'
      when: on_success
    - when: never

  before_script:
    - export PATH="$HOME/.local/bin:$PATH"
    - podman login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY

  script:
    - cd $DEPLOY_DIR
    - echo "▶️ Desplegando $REGISTRY/$IMAGE:$IMAGE_TAG en DEV"
    - sudo podman-compose -f $COMPOSE_FILE pull tecrep-monitor-local
    - sudo podman-compose -f $COMPOSE_FILE up -d --force-recreate tecrep-monitor-local