version: "2"

services:
  tecrep-monitor-local:
    build:
      context: .
    ports:
      - "8085:9090"
      - "9229:9229"  # Exponemos el puerto para el debugger
    container_name: tecrep-monitor-local
    environment:
      _API_EQUIPMENTS: http://localhost:10025
      _API_RESOURCES: http://localhost:10033
      _API_SERVICES: http://localhost:10007
      _API_ADDRESSES: http://localhost:10026
      KEYCLOAK_AUTH_PATH: http://localhost:8080
      KEYCLOAK_AUTH_REALM: monaco-telecom-dev
      KEYCLOAK_AUTH_CLIENT_PERMISSIONS: tecrep-monitor
      _UNM: 
      COMPANY: MT
      NODE_ENV: development  # Entorno de desarrollo
      NODE_OPTIONS: --use-openssl-ca --openssl-legacy-provider --inspect=0.0.0.0:9229
    # Sobrescribimos el comando para usar el debugger
    command: sh -c "npm run generate-envs-prod && node --inspect=0.0.0.0:9229 server.js"