version: "2"

services:
  tecrep-monitor-local:
    image: git.tigopa.local:5050/tigo/tecrep/monitor:toc
    ports:
      - "8083:8080"
    container_name: tecrep-monitor-local
    environment:
      _API_EQUIPMENTS: https://tecrep-monitor-dev.tigo.com.pa/equipments
      _API_RESOURCES: https://tecrep-monitor-dev.tigo.com.pa/resources
      _API_SERVICES: https://tecrep-monitor-dev.tigo.com.pa/services
      _API_ADDRESSES: 
      KEYCLOAK_AUTH_PATH: https://keycloack-dev.tigo.com.pa
      KEYCLOAK_AUTH_REALM: tigo-panama
      KEYCLOAK_AUTH_CLIENT_PERMISSIONS: tecrep-monitor
      _UNM: 
      COMPANY: MT
      NODE_ENV: development  # Entorno de desarrollo
      NODE_OPTIONS: --use-openssl-ca --openssl-legacy-provider --inspect=0.0.0.0:8080
    # Sobrescribimos el comando para usar el debugger

