import { numberStatus, numberStatusAdd } from './numberStatus';
import { yesNoFilter } from '../../yesNoFilter';
import { numberVanityCategory } from './numberVanityCategory';
import { numberNature } from './numberNature';

export const numberFields = [
  {
    id: 'numberId',
    infoPage: true,
    hidden: true,
  },
  {
    id: 'number',
    label: 'number.number',
    filterable: true,
    infoPage: true,
    addable: true,
  },
  {
    id: 'localPhoneNumber',
    label: 'number.localPhoneNumber',
    filterable: ['EIR'],
    infoPage: true,
    hidden: ['MT', 'EPIC'],
  },
  {
    id: 'status',
    label: 'number.status',
    type: 'enum',
    values: numberStatus,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'statusAdd',
    label: 'number.statusAdd',
    hidden: true,
    type: 'enum',
    values: numberStatusAdd,
    addable: true,
  },
  {
    id: 'serviceAssociated',
    label: 'equipment.serviceAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: ['MT', 'EPIC'],
    hidden: true,
  },
  {
    id: 'orderAssociated',
    label: 'equipment.orderAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: ['MT', 'EPIC'],
    hidden: true,
  },
  {
    id: 'vanityCategory',
    label: 'number.vanityCategory',
    type: 'enum',
    values: numberVanityCategory,
    editable: ['MT', 'EPIC', 'MALTA'],
    addable: true,
    filterable: ['MT', 'EPIC', 'MALTA'],
    infoPage: true,
    hidden: ['EIR'],
  },
  {
    id: 'activity',
    label: 'number.activity',
    type: 'enum',
    values: 'dynamic',
    hidden: true,
  },
  {
    id: 'activityService',
    label: 'number.activityService',
    type: 'enum',
    values: 'dynamic',
    filterable: ['MT', 'EPIC'],
    hidden: ['EIR'],
    infoPage: true,
  },
  {
    id: 'nature',
    label: 'number.nature',
    type: 'enum',
    values: numberNature,
    editable: ['MT', 'EPIC'],
    addable: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
    hidden: ['EIR'],
    infoPage: ['MT', 'EPIC'],
  },
  {
    id: 'inventoryPoolCode',
    label: 'number.inventoryPoolCode',
    type: 'enum',
    values: 'dynamic',
    hidden: ['MT'],
    editable: ['EPIC', 'EIR'],
    addable: ['EPIC', 'EIR'],
    filterable: ['EPIC', 'EIR'],
    infoPage: ['EPIC', 'EIR'],
  },
  {
    id: 'serviceId',
    label: 'number.serviceId',
    hidden: ['EIR'],
    infoPage: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
  },
  {
    id: 'orderId',
    label: 'number.orderId',
    editable: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
    hidden: ['EIR'],
    infoPage: ['MT', 'EPIC'],
    addable: false,
  },
  {
    id: 'rangeId',
    label: 'number.rangeId',
    filterable: ['MT', 'EPIC', 'MALTA'],
    infoPage: true,
    hidden: ['EIR'],
  },
  {
    id: 'swapReason',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'packId',
    label: 'number.packId',
    hidden: ['MT', 'EPIC', 'MALTA'],
    editable: ['EIR'],
    filterable: ['EIR'],
    infoPage: true,
  },
  {
    id: 'offerType',
    label: 'number.offerType',
    editable: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
    hidden: ['EIR'],
    infoPage: ['MT', 'EPIC'],
    addable: true,
  },
  {
    id: 'zone',
    label: 'number.zone',
    filterable: true,
    infoPage: true
  },
  {
    id: 'actions',
    label: '',
    cellProps: {style: {whiteSpace: 'nowrap'}},
  },
];
