import { simCardStatus } from './simCardStatus';
import { simCardNature } from './simCardNature';
import { yesNoFilter } from '../../yesNoFilter';

export const simCardFields = [
  {
    id: 'id',
    label: 'simcard.equipmentId',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'serialNumber',
    label: 'simcard.serialNumber',
    type: 'string',
    addable: true,
    filterable: true,
    editable: false,
    infoPage: true,
  },
  {
    id: 'esim',
    label: 'simcard.esim',
    type: 'enum',
    values: yesNoFilter,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'status',
    label: 'simcard.status',
    type: 'enum',
    values: simCardStatus,
    filterable: true,
    editable: false,
    infoPage: true,
  },
  {
    id: 'accessType',
    label: 'simcard.accessType',
    type: 'enum',
    values: 'dynamic',
    addable: true,
    filterable: ['MT','EPIC', 'MALTA'],
    infoPage: true,
    editable: ['EPIC'],
    hidden: ['EIR']
  },
  {
    id: 'activationDate',
    label: 'simcard.activationDate',
    type: 'date',
    infoPage: true
  },
  {
    id: 'imsiNumber',
    label: 'simcard.imsiNumber',
    type: 'number',
    editable: true,
    filterable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'imsiSponsorNumber',
    label: 'simcard.imsiSponsorNumber',
    type: 'number',
    editable: ['MT','EPIC', 'MALTA'],
    filterable: ['MT','EPIC', 'MALTA'],
    addable: true,
    infoPage: true,
    hidden: true
  },
  {
    id: 'plmnName',
    label: 'simcard.plmn',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'plmn',
    label: 'plmn.code',
    hidden: true,
    type: 'search',
    values: 'dynamic',
    addable: true,
  },
  {
    id: 'pin1Code',
    label: 'simcard.pin1Code',
    type: 'number',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'pin2Code',
    label: 'simcard.pin2Code',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'puk1Code',
    label: 'simcard.puk1Code',
    type: 'number',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'puk2Code',
    label: 'simcard.puk2Code',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'nature',
    label: 'simcard.nature',
    type: 'enum',
    values: simCardNature,
    addable: true,
    editable: true,
    filterable: ['MT', 'EPIC', 'MALTA'],
    infoPage: true,
  },
  {
    id: 'authKey',
    label: 'simcard.authKey',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'accessControlClass',
    label: 'simcard.accessControlClass',
    hidden: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'preactivated',
    label: 'simcard.preactivated',
    type: 'boolean',
    hidden: true,
    filterable: ['EIR', 'EPIC'],
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'serviceAssociated',
    label: 'equipment.serviceAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: ['MT', 'EPIC'],
    hidden: true,
    editable: false,
  },
  {
    id: 'orderAssociated',
    label: 'equipment.orderAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: ['MT', 'EPIC'],
    hidden: true,
    editable: false,
  },
  {
    id: 'preactivatedFlag',
    label: 'simcard.preactivatedFlag',
    hidden: ['MT'],
  },
  {
    id: 'batchNumber',
    label: 'simcard.batchNumber',
    addable: ['MT', 'EPIC'],
    filterable: true,
    infoPage: ['MT', 'EPIC'],
  },
  {
    id: 'brand',
    label: 'simcard.brand',
    addable: true,
    editable: true,
    filterable: true,
    infoPage: ['EPIC'],
    hidden: ['MT', 'EIR', 'MALTA']
  },
  {
    id: 'externalNumber',
    label: 'simcard.externalNumber',
    type: 'number',
    addable: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
    hidden: true,
    infoPage: ['MT', 'EPIC'],
  },
  {
    id: 'providerName',
    label: 'simcard.providerName',
    infoPage: ['MT', 'EPIC'],
    hidden: ['EIR', 'EPIC']
  },
  {
    id: 'provider',
    label: 'simcard.provider',
    hidden: true,
    type: 'enum',
    values: 'dynamic',
    addable: ['MT', 'EPIC', 'MALTA'],
    filterable: ['MT', 'EPIC'],
  },
  {
    id: 'warehouseName',
    label: 'simcard.warehouseName',
    infoPage: ['MT', 'EPIC'],
    hidden: true,
  },
  {
    id: 'warehouse',
    label: 'simcard.warehouse',
    hidden: true,
    type: 'enum',
    values: 'dynamic',
    editable: ['MT', 'EPIC'],
    addable: ['MT', 'EPIC'],
    filterable: ['MT', 'EPIC'],
  },
  {
    id: 'packId',
    label: 'simcard.packId',
    type: 'string',
    hidden: ['MT'],
    filterable: ['EPIC', 'EIR'],
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'inventoryPoolName',
    label: 'simcard.inventoryPoolCode',
    hidden: ['MT'],
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'inventoryPool',
    label: 'simcard.inventoryPool',
    hidden: true,
    type: 'enum',
    values: 'dynamic',
    addable: ['EIR', 'EPIC'],
    filterable: ['EIR', 'EPIC'],
  },
  {
    id: 'simProfile',
    label: 'simcard.simProfile',
    filterable: true,
    infoPage: true,
    editable: true
  },
  {
    id: 'orderId',
    label: 'simcard.orderId',
    editable: ['MT', 'EPIC'],
    hidden: ['EIR'],
    filterable: ['MT', 'EPIC'],
    addable: ['MT', 'EPIC'],
    infoPage: ['MT', 'EPIC'],
  },
  {
    id: 'serviceId',
    label: 'simcard.serviceId',
    type: 'number',
    filterable: ['MT', 'EPIC'],
    hidden: true,
    editable: false,
    infoPage: ['MT', 'EPIC'],
  },
  {
    id: 'serviceAccessLink',
    label: 'simcard.serviceId',
  },
  {
    id: 'allotmentId',
    label: 'simcard.allotmentId',
    filterable: ['EIR', 'EPIC'],
    hidden: true,
    type: 'number',
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'number',
    label: 'simcard.number',
    hidden: true,
    infoPage: ['EIR', 'EPIC'],
    editable: ['EIR']
  },
  {
    id: 'transportKey',
    hidden: true,
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'algorithmVersion',
    hidden: true,
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'checkDigit',
    hidden: true,
    infoPage: ['EIR', 'EPIC'],
  },
  {
    id: 'actions',
    label: '',
    cellProps: {
      style: {
        whiteSpace: 'nowrap',
      },
    },
  },
];
