import { cpeStatus } from '../cpe/cpeStatus';
import { yesNoFilter } from '../../yesNoFilter';
import { cpeNature } from '../cpe/cpeNature';
import { ancillaryEquipmentName } from './ancillaryEquipmentName';

export const ancillaryEquipmentFields = [
  {
    id: 'id',
    label: 'ancillaryEquipment.id',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'category',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'serialNumber',
    label: 'ancillaryEquipment.serialNumber',
    filterable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'status',
    label: 'ancillaryEquipment.status',
    type: 'enum',
    values: cpeStatus,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'accessType',
    label: 'ancillaryEquipment.accessType',
    type: 'enum',
    values: 'dynamic',
    filterable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'activationDate',
    label: 'ancillaryEquipment.activationDate',
    type: 'date',
    infoPage: true
  },
  {
    id: 'equipmentName',
    label: 'ancillaryEquipment.equipmentName',
    type: 'enum',
    addable: true,
    filterable: true,
    values: ancillaryEquipmentName,
    infoPage: true,
  },
  {
    id: 'equipmentAssociated',
    label: 'equipment.equipmentAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: true,
    hidden: true,
  },
  {
    id: 'orderAssociated',
    label: 'equipment.orderAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: true,
    hidden: true,
  },
  {
    id: 'macAddress',
    label: 'ancillaryEquipment.macAddress',
    filterable: true,
    editable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'provider',
    label: 'ancillaryEquipment.provider',
    type: 'enum',
    values: 'dynamic',
    filterable: true,
    hidden: true,
  },
  {
    id: 'providerName',
    label: 'ancillaryEquipment.provider',
    infoPage: true,
  },
  {
    id: 'warehouseName',
    label: 'ancillaryEquipment.warehouse',
    infoPage: true,
  },
  {
    id: 'warehouse',
    label: 'ancillaryEquipment.warehouse',
    type: 'enum',
    values: 'dynamic',
    filterable: true,
    addable: true,
    editable: true,
    hidden: true
  },
  {
    id: 'serviceId',
    label: 'ancillaryEquipment.serviceId',
    filterable: true,
    infoPage: true,
  },
  {
    id: 'model',
    label: 'ancillaryEquipment.model',
    type: 'enum',
    values: 'dynamic',
    filterable: true,
    editable: false,
    addable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'nature',
    label: 'ancillaryEquipment.nature',
    type: 'enum',
    values: cpeNature,
    filterable: true,
    addable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'pairedEquipmentId',
    label: 'ancillaryEquipment.pairedEquipmentId',
    type: 'number',
    filterable: true,
    editable: false,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'pairedEquipmentLink',
    label: 'ancillaryEquipment.pairedEquipmentId',
    hidden: 'condition',
  },
  {
    id: 'pairedEquipmentCategory',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'orderId',
    label: 'ancillaryEquipment.orderId',
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'independent',
    label: 'ancillaryEquipment.independent',
    type: 'boolean',
    editable: true,
    hidden: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'independentFilter',
    label: 'ancillaryEquipment.independent',
    hidden: true,
    filterable: true,
    type: 'enum',
    values: yesNoFilter,
  },
  {
    id: 'sfpVersion',
    label: 'ancillaryEquipment.sfpVersion',
    hidden: true,
    addable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'externalNumber',
    label: 'ancillaryEquipment.externalNumber',
    type: 'number',
    infoPage: true,
    filterable: true,
    hidden: true,
  },
  {
    id: 'recyclable',
    label: 'ancillaryEquipment.recyclable',
    type: 'boolean',
    hidden: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'preactivated',
    infoPage: true,
    hidden: true,
  },
  {
    id: 'batchNumber',
    label: 'ancillaryEquipment.batchNumber',
    hidden: true,
    addable: true,
    infoPage: true,
    filterable: true,
  },
  {id: 'actions', label: '', cellProps: {style: {whiteSpace: 'nowrap'}}},
];
