import { serviceStatus } from './serviceStatus';
export const serviceFields = [
  {
    id: 'crmServiceId',
    label: 'service.crmServiceId',
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'customerNo',
    label: 'service.customer',
    type: 'number',
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'serviceActivity',
    label: 'service.serviceActivity',
    type: 'enum',
    values: 'dynamic',
    filterable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'status',
    label: 'service.status',
    type: 'enum',
    values: serviceStatus,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'number',
    label: 'service.number',
    filterable: true,
    infoPage: true,
  },
  {
    id: 'numberLink',
    hidden: true,
    label: 'service.number',
  },
  {
    id: 'mainRangeId',
    label: 'service.mainRangeId',
    filterable: true,
    infoPage: true,
  },
  {
    id: 'activationDate',
    label: 'service.activationDate',
    hidden: true,
    filterable: true,
    type: 'date',
    infoPage: true,
  },
  {
    id: 'activation',
    label: 'service.activationDate',
  },
  {
    id: 'onGoingAction',
    label: 'service.onGoingAction',
    type: 'boolean',
    filterable: false,
    infoPage: true,
  },
  {
    id: 'serviceId',
    label: 'service.serviceId',
    type: 'number',
    filterable: true,
    hidden: true,
    infoPage: true,
  },
  {id: 'subscriptionId', hidden:true, infoPage:true},
  {id: 'serviceCategory', hidden:true, infoPage:true},
  {id: 'creationDate', hidden:true, infoPage:true},
  {id: 'deactivationDate', hidden:true, infoPage:true},
  {id: 'suspensionDate', hidden:true, infoPage:true},
  {id: 'resumedDate', hidden:true, infoPage:true},
  {id: 'cancellationDate', hidden:true, infoPage:true},
  {id: 'barringDate', hidden:true, infoPage:true},
  {id: 'serviceOrderId', hidden:true, infoPage:true},
  {id: 'actionRequest', hidden:true, infoPage:true},
  {id: 'dateRequest', hidden:true, infoPage:true},
  {id: 'reasonRequest', hidden:true, infoPage:true},
  {id: 'actionPlanned', hidden:true, infoPage:true},
  {id: 'plannedDate', hidden:true, infoPage:true},
  {id: 'serviceActionStatus', hidden:true, infoPage:true},
  {id: 'actionStart', hidden:true, infoPage:true},
  {id: 'actionEnd', hidden:true, infoPage:true},
  {
    id: 'techId',
    label: 'service.access.techId',
    filterable: true,
    editable: true,
    hidden: true,
    infoPage: true
  }
];
