export const ServiceEntityTypes = {
  PROVISIONING_TAGS: 'PROVISIONING_TAGS',
  ACTIVATION_CODE: 'ACTIVATION_CODE',
  JOBS: 'SERVICE_JOBS',
  TAGS_AND_CODES: 'TAGS_AND_CODES',
  ASSOCIATED_PROVISIONING_TAGS: 'ASSOCIATED_PROVISIONING_TAGS',
  ASSOCIATED_ACTIVATION_CODES: 'ASSOCIATED_ACTIVATION_CODES',
  PROVISIONING_PRODUCT: 'PROVISIONING_PRODUCT',
  PROVISIONING_TAG_ACTION_PARAMETERS: 'PROVISIONING_TAG_ACTION_PARAMETERS',
  PROVISIONING_TAG_ACTION: 'PROVISIONING_TAG_ACTION'
};
