export const EquipmentJobFields = [
    { id: 'id', label: 'id', hidden: true, infoPage: true },
    {
        id: 'operation',
        label: 'jobConfiguration.operation',
        filterable: true,
        type: 'enum',
        values: [
            { id: 'operationAll', key: '', value: 'all' },
            { id: 'auditClean', key: 'AUDIT_CLEAN', value: 'AUDIT_CLEAN' },
            { id: 'eqt_purge', key: 'EQT_PURGE', value: 'EQT_PURGE' },
            { id: 'eqt_unbook', key: 'EQT_UNBOOK', value: 'EQT_UNBOOK' },
        ],
        addable: true,
        editable: true,
        infoPage: true,
    },
    {
        id: 'status',
        label: 'jobConfiguration.status',
        filterable: true,
        type: 'enum',
        values: [
            { id: 'all', key: '', value: 'all' },
            { id: 'instore', key: 'INSTORE', value: 'INSTORE' },
            { id: 'available', key: 'AVAILABLE', value: 'AVAILABLE' },
            { id: 'booked', key: 'BOOKED', value: 'BOOKED' },
            { id: 'assigned', key: 'ASSIGNED', value: 'ASSIGNED' },
            { id: 'activated', key: 'ACTIVATED', value: 'ACTIVATED' },
            { id: 'onhold', key: 'ONHOLD', value: 'ONHOLD' },
            { id: 'returned', key: 'RETURNED', value: 'RETURNED' },
            { id: 'notreturned', key: 'NOTRETURNED', value: 'NOTRETURNED' },
            { id: 'deprecated', key: 'DEPRECATED', value: 'DEPRECATED' },
            { id: 'repackaging', key: 'REPACKAGING', value: 'REPACKAGING' },
            { id: 'deactivated', key: 'DEACTIVATED', value: 'DEACTIVATED' },
            { id: 'final', key: 'FINAL', value: 'FINAL' },
        ],
        addable: true,
        editable: true,
        infoPage: true,
    },
    {
        id: 'recyclable',
        label: 'jobConfiguration.recyclable',
        filterable: true,
        type: 'enum',
        values: [
            { id: 'all', key: '', value: 'all' },
            { id: 'yes', key: 'true', value: 'yes' },
            { id: 'no', key: 'false', value: 'no' },
        ],
        addable: true,
        editable: true,
        infoPage: true,
    },
    { id: 'days', label: 'jobConfiguration.days', addable: true, editable: true, infoPage: true },
    {
        id: 'enabled',
        label: 'jobConfiguration.enabled',
        filterable: true,
        type: 'enum',
        values: [
            { id: 'all', key: '', value: 'all' },
            { id: 'yes', key: 'true', value: 'yes' },
            { id: 'no', key: 'false', value: 'no' },
        ],
        addable: true,
        editable: true,
        infoPage: true,
    },
];
