export const StatusChangeEnum = Object.freeze({
  assign: 'assign',
  activate: 'activate',
  available: 'available',
  book: 'book',
  portOut: 'portOut',
  lockUser: 'lockUser',
  lockZone: 'lockZone',
  free: 'free',
  unlockUser: 'unlockUser',
  unlockZone: 'unlockZone',
  unassign: 'unassign',
  deactivate: 'deactivate',
  rollbackActivate: 'rollbackActivate',
  rollbackDeactivate: 'rollbackDeactivate',
  purged: 'purged',
  repatriate: 'repatriate',
  pair: 'pair',
  unpair: 'unpair',
  delete: 'delete',
  rollbackDelete: 'rollbackDelete',
  portIn: 'portIn',
});
