export const productActions = [
  {id: 'all', key: '', value: 'all'},
  {id: 'firstActivation', key: 'FIRST_ACTIVATION', value: 'FIRST_ACTIVATION'},
  {id: 'activation', key: 'ACTIVATION', value: 'ACTIVATION'},
  {id: 'transition', key: 'TRANSITION', value: 'TRANSITION'},
  {id: 'migration', key: 'MIGRATION', value: 'MIGRATION'},
  {id: 'deactivation', key: 'DEACTIVATION', value: 'DEACTIVATION'},
  {id: 'chgeNum', key: 'CHGE_NUM', value: 'CHGE_NUM'},
  {id: 'chgeEqt', key: 'CHGE_EQT', value: 'CHGE_EQT'},
  {id: 'returnEqt', key: 'RETURN_EQT', value: 'RETURN_EQT'},
  {id: 'chgeAddr', key: 'CHGE_ADDR', value: 'CHGE_ADDR'},
  {id: 'chgeCli', key: 'CHGE_CLI', value: 'CHGE_CLI'},
  {id: 'barring', key: 'BARRING', value: 'BARRING'},
  {id: 'unbarring', key: 'UNBARRING', value: 'UNBARRING'},
  {id: 'suspCli', key: 'SUSP_CLI', value: 'SUSP_CLI'},
  {id: 'resumCli', key: 'RESUM_CLI', value: 'RESUM_CLI'},
  {id: 'suspOper', key: 'SUSP_OPER', value: 'SUSP_OPER'},
  {id: 'resumOper', key: 'RESUM_OPER', value: 'RESUM_OPER'},
  {id: 'resetCell', key: 'RESET_CELL', value: 'RESET_CELL'},
  {id: 'returnAncil', key: 'RETURN_ANCIL', value: 'RETURN_ANCIL'},
  {id: 'chgeAncil', key: 'CHGE_ANCIL', value: 'CHGE_ANCIL'},
  {id: 'transfer', key: 'TRANSFER', value: 'TRANSFER'},
  {id: 'addQty', key: 'ADD_QTY', value: 'ADD_QTY'},
  {id: 'delQty', key: 'DEL_QTY', value: 'DEL_QTY'},
];
