import { cpeStatus } from './cpeStatus';
import { yesNoFilter } from '../../yesNoFilter';
import { cpeNature } from './cpeNature';

export const cpeFields = [
  {
    id: 'id',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'category',
    hidden: true,
    infoPage: true,
  },
  {
    id: 'serialNumber',
    label: 'cpe.serialNumber',
    filterable: true,
    addable: true,
    infoPage: true,
  },
  {
    id: 'status',
    label: 'cpe.status',
    type: 'enum',
    values: cpeStatus,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'accessType',
    label: 'cpe.accessType',
    type: 'enum',
    values: 'dynamic',
    addable: true,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'activationDate',
    label: 'cpe.activationDate',
    type: 'date',
    infoPage: true
  },
  {
    id: 'serviceAssociated',
    label: 'equipment.serviceAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: true,
    hidden: true,
  },
  {
    id: 'orderAssociated',
    label: 'equipment.orderAssociated',
    type: 'enum',
    values: yesNoFilter,
    filterable: true,
    hidden: true,
  },
  {
    id: 'macAddressCpe',
    label: 'cpe.macAddressCpe',
    addable: true,
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'macAddressRouter',
    label: 'cpe.macAddressRouter',
    addable: true,
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'macAddressVoip',
    label: 'cpe.macAddressVoip',
    addable: true,
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'macAddressLan',
    label: 'cpe.macAddressLan',
    addable: true,
    filterable: true,
    editable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'macAddress5G',
    label: 'cpe.macAddress5G',
    addable: true, filterable: true,
    editable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'macAddress4G',
    label: 'cpe.macAddress4G',
    addable: true, filterable: true,
    editable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'hwVersion',
    label: 'cpe.hwVersion',
    hidden: true,
    addable: true,
    filterable: true,
    editable: true,
    infoPage: true,
  },
  {
    id: 'batchNumber',
    label: 'cpe.batchNumber',
    addable: true,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'model',
    label: 'cpe.model',
    type: 'enum',
    values: 'dynamic',
    hidden: true,
    addable: true,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'providerName',
    label: 'cpe.providerName',
    infoPage: true,
  },
  {
    id: 'provider',
    label: 'cpe.provider',
    hidden: true,
    type: 'enum',
    values: 'dynamic',
    addable: true,
    filterable: true,
  },
  {
    id: 'warehouseName',
    label: 'cpe.warehouseName',
    infoPage: true,
  },
  {
    id: 'warehouse',
    label: 'cpe.warehouse',
    hidden: true,
    type: 'enum',
    values: 'dynamic',
    editable: true,
    filterable: true,
    addable: true,
  },
  {
    id: 'nature',
    label: 'cpe.nature',
    type: 'enum',
    values: cpeNature,
    addable: true,
    filterable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'orderId',
    label: 'cpe.orderId',
    editable: true,
    filterable: true,
    infoPage: true,
  },
  {
    id: 'serviceId',
    label: 'serviceId',
    filterable: true,
    hidden: true,
    infoPage: true,
  },
  {
    id: 'serviceAccessLink',
    label: 'cpe.serviceId',
  },
  {
    id: 'externalNumber',
    label: 'cpe.externalNumber',
    type: 'number',
    infoPage: true,
    hidden: true,
    filterable: true,
  },
  {
    id: 'recyclable',
    infoPage: true,
    hidden: true,
  },
  {
    id: 'preactivated',
    infoPage: true,
    hidden: true,
  },
  {
    id: 'chipsetId',
    infoPage: true,
    hidden: true,
  },
  {
    id: 'actions',
    label: '',
    cellProps: {style: {whiteSpace: 'nowrap'}},
  },
];
